name: Chestnut
version: '${version}'
main: xyz.bellbot.chestnut.Chestnut
description: A flexible Minecraft Paper plugin that lets you track any block’s state or interactions and send custom Discord webhook alerts with your own message templates.
author: Penicilin
website: https://bellbot.xyz
api-version: '1.21'
commands:
  track:
    description: Manage Chestnut trackers
    usage: "/track help"
    permission: chestnut.use
permissions:
  chestnut.use:
    description: Use /track commands for owned trackers
    default: true
  chestnut.admin:
    description: Administer any tracker and manage plugin
    default: op
