name: Build (test)

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle (with caching)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chestnut-build-${{ github.run_number }}
          path: build/libs/*.jar
          if-no-files-found: error
