name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag/version (e.g., v0.1.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: true
        default: false
        type: boolean
      changelog:
        description: 'Release notes'
        required: false
        default: ''
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle (with caching)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Verify artifact exists
        run: ls -lh build/libs && test -n "$(ls -1 build/libs/*.jar 2>/dev/null)"

      - name: Create GitHub Release and upload jar
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          target_commitish: master
          name: ${{ inputs.version }}
          body: ${{ inputs.changelog }}
          prerelease: ${{ inputs.prerelease }}
          files: build/libs/*.jar
